services:
  - name: nginx-blue
    type: Service
    selectors:
      app: nginx
      version: blue
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
  - name: nginx-green
    type: Service
    selectors:
      app: nginx
      version: green
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80

deployments:
  - name: nginx-blue
    type: Deployment
    replicas: 3
    selector:
      matchLabels:
        app: nginx
        version: blue
    template:
      metadata:
        labels:
          app: nginx
          version: blue
      spec:
        containers:
          - name: nginx
            image: nginx:1.16.1
            ports:
              - containerPort: 80
  - name: nginx-green
    type: Deployment
    replicas: 3
    selector:
      matchLabels:
        app: nginx
        version: green
    template:
      metadata:
        labels:
          app: nginx
          version: green
      spec:
        containers:
          - name: nginx
            image: nginx:1.21.3
            ports:
              - containerPort: 80

ingress:
  - name: nginx-ingress
    type: Ingress
    rules:
      - http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: nginx-blue
                  port:
                    number: 80
