apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-agent
  labels:
    app: datadog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog
  template:
    metadata:
      labels:
        app: datadog
    spec:
      containers:
        - name: datadog-agent
          image: datadog/agent:latest  # Replace 'latest' with a specific version if needed
          env:
            - name: DD_API_KEY  # Replace with your Datadog API Key
              value: "<YOUR_DATADOG_API_KEY>"
          volumeMounts:
            - name: datadog-agent-config
              mountPath: /etc/datadog-agent
      volumes:
        - name: datadog-agent-config
          configMap:
            name: datadog-agent-config
---
apiVersion: v1
kind: Service
metadata:
  name: datadog-agent-service
spec:
  selector:
    app: datadog
  ports:
    - protocol: TCP
      port: 8125
      targetPort: 8125
    - protocol: TCP
      port: 8126
      targetPort: 8126
    - protocol: TCP
      port: 8127
      targetPort: 8127
    - protocol: TCP
      port: 8128
      targetPort: 8128
    - protocol: TCP
      port: 8129
      targetPort: 8129
