apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: identityproviders.security.cloud.google.com
spec:
  group: security.cloud.google.com
  names:
    kind: IdentityProvider
    listKind: IdentityProviderList
    plural: identityproviders
    singular: identityprovider
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                authentication:
                  type: object
                  properties:
                    type:
                      type: string
                    oidc:
                      type: object
                      properties:
                        issuerUri:
                          type: string
                serviceAccount:
                  type: string
            status:
              type: object
              properties:
                lastObservedTime:
                  type: string
                  format: date-time
      subresources:
        status: {}
